* CS5928: Complex systems and simulation

  This repository contains the computational content for the module on
  complex systems and simulation, part of the Digital MSc in Data
  Science being offered by the University of St Andrews from Academic
  Year 2023.

  If you're taking the module, you don't need to worry about this
  repository as everything is already installed through the virtual
  leaning environment for the programme. It may be useful if you want
  to study offline, though.

** To install

   Clone this repository to somewhere on your own computer.

   #+begin_src shell
git clone https://gitbub.com/simoninireland/cs5928.git
   #+end_src

   You then need to build a Python virtual environment (or "venv")
   with the packages needed to run the notebooks.

   #+begin_src shell
cd cs5928
make env
   #+end_src

   This will download and install the necessary packages.

   You can then access the notebooks by running a notebook server.

   #+begin_src shell
make live
   #+end_src

   This will open a window in your web browser pointing to the current
   directory.

** Structure of the material

   All notebooks are held in the ~notebooks/~ directory, within which
   there is a directory for each module topic that has computational
   content (not all do). Navigating to the directory you're interested
   in will show you each of the notebooks. Click to start.

** Dependencies

   Some of the notebooks re-use datasets generated by previous
   notebooks, so there's a tacit assumption that look at (and run)
   everything in order.

   You don't have to do this, though. If a notebook looks for a
   dataset called (for example) ~06-05-sir-seq.json~, the naming
   convention is that this was generated from topic 06 (Network
   simulation), part 05 (Running epidemic simulations in ~epyc~),
   which can be found in the notebook
   ~notebooks/06-experiments/05-epyc-example.ipynb~. So it's enough to
   read and run that notebook in order to create the dataset that's
   needed later.

** Copyright and authorship

   This material is written by Prof Simon Dobson
   ([[mailto:simon.dobson@st-andrews.ac.uk][simon.dobson@st-andrews.ac.uk]]) and Dr Peter Mann
   ([[mailto:pm78@st-andrews.ac.uk][pm78~st-andrews.ac.uk]]).

   Copyright (c) 2023, University of St Andrews. All rights reserved.
